{
  imports = [
    ./ai.nix
    ./attic.nix
    ./cachix.nix
    ./common.nix
    ./fonts.nix
    ./games.nix
    ./hyprland.nix
    ./kernel.nix
    ./minikube.nix
    ./network.nix
    ./nixpkgs.nix
    ./os.nix
    ./pcsc.nix
    ./pipewire.nix
    ./programs.nix
    ./shell.nix
    ./ssh.nix
    ./virtual.nix
  ];
}
